* se agrega al script clean-squid la comprobacion de privilegios de root

diff --git a/clean-squid b/clean-squid
--- a/clean-squid
+++ b/clean-squid
@@ -1,5 +1,9 @@
 #!/bin/bash
 #elaborado por sinfallas
+if [[ $USER != root ]]; then
+echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
+exit 1
+fi
 service squid3 stop
 rm -rfv /var/spool/squid3/*
 squid3 -z
